version: '3.0'
services:
  rediscache:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    hostname: 'rediscache'
    container_name: 'rediscache'
  serviceregistry:
    build:
      context: ./serviceregistry
    image: 'serviceregistry:0.1'
    ports:
      - '8761:8761'
    hostname: 'serviceregistry'
    container_name: 'serviceregistry'
  gateway:
    build:
      context: ./gateway
    image: 'gateway:0.1'
    ports:
      - '8765:8765'
    hostname: 'gateway'
    container_name: 'gateway'
  movieservice:
    build:
      context: ./movieservice
    image: 'movieservice:0.1'
    depends_on:
      - rediscache
      - configservice
      - serviceregistry
  inventoryservice:
    build:
      context: ./inventoryservice
    image: 'inventoryservice:0.1'
    depends_on:
      - rediscache
      - configservice
      - serviceregistry
  userservice:
    build:
      context: ./userservice
    image: 'userservice:0.1'
    depends_on:
      - rediscache
      - configservice
      - serviceregistry
networks:
  default:
    external:
      name: micronet                
