spring:
  profiles: default
  datasource:
    url: jdbc:mysql://192.168.1.3:3306/sakila
    username: sakilaflix
    password: thappu
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: rabbitmq
  cloud:
    config:
      uri: http://configservice:8888
      fail-fast: false
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    service-url:
     defaultZone: http://serviceregistry:8761/eureka
management:
  security:
    enabled: false