spring:
  datasource:
    url: jdbc:mysql://192.168.1.3:3306/sakila
    username: sakilaflix
    password: thappu
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: rabbitmq
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    inetutils:
      preferredNetworks:
      - 192.168
      - 10.0
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    service-url:
     defaultZone: http://serviceregistry:8761/eureka
management:
  security:
    enabled: false
microflix:
  rediscache: "redis://rediscache:6379"